"""empty message

Revision ID: 17d51009043a
Revises: a5a800e64fdb
Create Date: 2023-11-01 18:58:48.581068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17d51009043a'
down_revision = 'a5a800e64fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pms_wanted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('devs_wanted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('designers_wanted', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_skills', postgresql.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('other_skills')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('designers_wanted')
        batch_op.drop_column('devs_wanted')
        batch_op.drop_column('pms_wanted')

    # ### end Alembic commands ###
