"""empty message

Revision ID: 1e160b44e01f
Revises: 2df3323deb65
Create Date: 2023-10-17 00:56:43.062174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e160b44e01f'
down_revision = '2df3323deb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_project_id_fkey', type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_project_id_fkey', 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###
