"""empty message

Revision ID: 5b9017255b14
Revises: 
Create Date: 2023-10-15 11:52:49.994327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b9017255b14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=100), nullable=True),
    sa.Column('apitoken', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('prev_role', sa.String(length=100), nullable=True),
    sa.Column('prev_exp', sa.String(length=100), nullable=True),
    sa.Column('mentor', sa.Boolean(), nullable=True),
    sa.Column('prod_role', sa.String(length=100), nullable=True),
    sa.Column('prod_exp', sa.String(length=100), nullable=True),
    sa.Column('adjectives', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('about', sa.String(length=500), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('hours_wk', sa.String(length=100), nullable=True),
    sa.Column('availability', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('design_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('developer_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('management_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('wanted_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('linkedin', sa.String(length=100), nullable=True),
    sa.Column('github', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apitoken'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
