"""empty message

Revision ID: bab6633aa0f6
Revises: 93e06eaed1f9
Create Date: 2023-10-26 22:47:29.765242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab6633aa0f6'
down_revision = '93e06eaed1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('duedate', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('todos_users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'todo', ['todo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('todo')
    # ### end Alembic commands ###
