"""empty message

Revision ID: dba5ee008288
Revises: 1e160b44e01f
Create Date: 2023-10-17 19:29:17.503001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba5ee008288'
down_revision = '1e160b44e01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('projects_admin_id_fkey', type_='foreignkey')
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['current_project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_project_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('projects_admin_id_fkey', 'user', ['admin_id'], ['id'])

    # ### end Alembic commands ###
