"""empty message

Revision ID: dd2fa4d4c470
Revises: 4087fffa7029
Create Date: 2023-10-18 20:30:48.532347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2fa4d4c470'
down_revision = '4087fffa7029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key('fk_projects_user', 'user', ['admin_id'], ['id'], use_alter=True)

    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_projects', 'projects', ['current_project_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_projects', type_='foreignkey')

    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_user', type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
