"""empty message

Revision ID: f11545b748d3
Revises: bab6633aa0f6
Create Date: 2023-10-29 10:16:01.817851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11545b748d3'
down_revision = 'bab6633aa0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=500), nullable=True))
        batch_op.drop_column('link')

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
